/* =======================================================================
   GOLD_MVP_V0.6.4 — Query final (Layout Rigoroso Power BI)
   Autor Original: Miguel Alvarez Primo
   Adaptação: Engenheiro de Dados Sênior (Gemini)
   -----------------------------------------------------------------------
   Mudanças V0.6.4:
    - Garantia da ordem exata das colunas conforme TBL_RANK_TEC existente.
    - Coluna [RE] forçada para VARCHAR(20).
    - Mapeamento explícito coluna a coluna no STEP 7.
   -----------------------------------------------------------------------
*/

/* =========================
   PARÂMETROS GERAIS
   ========================= */
DECLARE @DESLOC INT = 0;
DECLARE @StartDate DATE = CAST(GETDATE() - 30 - @DESLOC AS DATE);
DECLARE @EndDate   DATE = CAST(GETDATE() - @DESLOC AS DATE);
DECLARE @VersaoRegra NVARCHAR(20) = N'V0.6.4'; -- Versão atualizada
DECLARE @DataExecucao DATETIME = GETDATE();
DECLARE @Days_Login_Window INT = 7;

DECLARE @Peso_Dimensao_Prod  FLOAT = 1;
DECLARE @Peso_Dimensao_Tempo FLOAT = 1;
DECLARE @Meta_Pontos_Max     FLOAT = 1;

DECLARE @wEtapa_Atrib  FLOAT = 0.04;
DECLARE @wEtapa_Aceite FLOAT = 0.08;
DECLARE @wEtapa_Site   FLOAT = 0.40;
DECLARE @wEtapa_Baixa  FLOAT = 0.08;
DECLARE @wBonus_Completo FLOAT = 0.10;
DECLARE @wBonus_Final    FLOAT = 0.20;

DECLARE @Treshold_Min INT = 15;
DECLARE @Tier1_Min INT = 60;   DECLARE @Pt_Tier1 FLOAT = 0.20;
DECLARE @Tier2_Min INT = 120;  DECLARE @Pt_Tier2 FLOAT = 0.10;
DECLARE @Tier3_Min INT = 180;  DECLARE @Pt_Tier3 FLOAT = 0.05;
DECLARE @Tier4_Min INT = 240;  DECLARE @Pt_Tier4 FLOAT = 0.01;
DECLARE @Pt_Tier5  FLOAT = 0.00;

DECLARE @pen_Reatrib  FLOAT = -0.00;
DECLARE @pen_Perda    FLOAT = -0.00;
DECLARE @pen_Aband    FLOAT = -0.00;
DECLARE @pen_Fora     FLOAT = -0.00;
DECLARE @pen_Onera    FLOAT = -0.00;
DECLARE @pen_Teleport FLOAT = -0.00;

DECLARE @OutlierMultiplier FLOAT = 1.5;
DECLARE @OutlierExtreme    FLOAT = 3.0;

-- Define a data de referência da carga (importante para anomes/anomessemana)
DECLARE @Carga_Ref_Data DATETIME = CAST(@EndDate AS DATETIME);

/* =========================
   STEP 0 — DIM TÉCNICOS
   ========================= */
DROP TABLE IF EXISTS #DIM_TECNICOS_RAW;
SELECT
  NOME AS NOME_TECNICO,
  EMPRESA_NOME AS EMPRESA,
  REGIONAL,
  UF AS UF_TEC,
  USUARIO AS RE_MATRICULA, -- AQUI: USUARIO na tabela dimensão é o RE
  CASE
    WHEN TIPO_USUARIO = 'TECNICO PE' THEN 'RE'
    WHEN TIPO_USUARIO = 'TECNICO PI' THEN 'PI'
    ELSE 'PI/RE'
  END AS TIPO_TEC
INTO #DIM_TECNICOS_RAW
FROM GENESIS.dbo.TBF_TECNICOS_GERAL;

-- Ajuste para garantir unicidade pelo RE, embora RE deva ser único por natureza
DROP TABLE IF EXISTS #DIM_TECNICOS_FINAL;
WITH CtsRE AS (
  SELECT RE_MATRICULA, COUNT(*) AS Qtd
  FROM #DIM_TECNICOS_RAW
  GROUP BY RE_MATRICULA
)
SELECT R.*,
       CASE WHEN C.Qtd = 1 THEN 1 ELSE 0 END AS FL_RE_UNICO
INTO #DIM_TECNICOS_FINAL
FROM #DIM_TECNICOS_RAW R
JOIN CtsRE C ON C.RE_MATRICULA = R.RE_MATRICULA;

/* =========================
   STEP 0.1 — NORMALIZAÇÃO & PERÍODOS (temps)
   ========================= */
-- MUDANÇA CRÍTICA: Lendo o campo RE da TBL_PROC ao invés do USUARIO
DROP TABLE IF EXISTS #PROC_PERIODO;
SELECT
  P.NUM_OS,
  P.RE, -- Alterado de USUARIO para RE (Chave Forte)
  P.DATA,
  UPPER(
    REPLACE(
      REPLACE(CONVERT(VARCHAR(200), P.TIPO_PROC) COLLATE Latin1_General_CI_AI,
              'PRÉ-BAIXA','PRE-BAIXA'),
      ' ',' '
    )
  ) AS TIPO_PROC_NORM,
  P.GEO_PROC
INTO #PROC_PERIODO
FROM GENESIS.dbo.TBL_PROC P
WHERE P.DATA >= @StartDate
  AND P.DATA <  DATEADD(DAY, 1, @EndDate)
  AND P.RE IS NOT NULL; -- Garante que não pegamos lixo sem RE

DROP TABLE IF EXISTS #PROC_LOGIN_WINDOW;
SELECT
  P.NUM_OS,
  P.RE, -- Alterado de USUARIO para RE
  P.DATA,
  UPPER(
    REPLACE(
      REPLACE(CONVERT(VARCHAR(200), P.TIPO_PROC) COLLATE Latin1_General_CI_AI,
              'PRÉ-BAIXA','PRE-BAIXA'),
      ' ',' '
    )
  ) AS TIPO_PROC_NORM,
  P.GEO_PROC
INTO #PROC_LOGIN_WINDOW
FROM GENESIS.dbo.TBL_PROC P
WHERE P.DATA >= CASE
                  WHEN DATEADD(DAY, -@Days_Login_Window, @EndDate) > @StartDate
                       THEN DATEADD(DAY, -@Days_Login_Window, @EndDate)
                  ELSE @StartDate
                END
  AND P.DATA <  DATEADD(DAY, 1, @EndDate)
  AND P.RE IS NOT NULL;


/* ============================================================
   [V0.6.4] Performance Indices (Atualizados para RE)
   ============================================================ */

CREATE INDEX IX_PROC_PERIODO_OS_RE          ON #PROC_PERIODO (NUM_OS, RE);
CREATE INDEX IX_PROC_PERIODO_EVENT_SEEK     ON #PROC_PERIODO (NUM_OS, RE, TIPO_PROC_NORM, DATA);
CREATE INDEX IX_PROC_PERIODO_RE_DATE        ON #PROC_PERIODO (RE, DATA);

-- Conjunto de OS/RE deduplicado
DROP TABLE IF EXISTS #DU;
SELECT DISTINCT NUM_OS, RE
INTO #DU
FROM #PROC_PERIODO;

CREATE CLUSTERED INDEX CX_DU ON #DU (NUM_OS, RE);

-- OP_ONE Mantém lógica por NUM_OS (independente do técnico)
DROP TABLE IF EXISTS #OP_ONE;
WITH op_rank AS (
  SELECT
    OP.NUM_OS,
    OP.EMPRESA,
    OP.UF_EVENTO,
    OP.REGIONAL_EVENTO,
    ROW_NUMBER() OVER (PARTITION BY OP.NUM_OS ORDER BY OP.NUM_OS) AS rn
  FROM GENESIS.dbo.TBL_OS_PAGAMENTO OP
)
SELECT NUM_OS, EMPRESA, UF_EVENTO, REGIONAL_EVENTO
INTO #OP_ONE
FROM op_rank
WHERE rn = 1;

CREATE CLUSTERED INDEX CX_OP_ONE ON #OP_ONE (NUM_OS);

/* ============================================================
   [V0.6.4] Consolidação única por (NUM_OS, RE)
   ============================================================ */

-- Datas mínimas por etapa
DROP TABLE IF EXISTS #EVT_MIN;
SELECT
  P.NUM_OS,
  P.RE,
  MIN(CASE WHEN P.TIPO_PROC_NORM IN ('ATRIBUIÇÃO','ATRIBUICAO')                 THEN P.DATA END) AS DT_ATRIB,
  MIN(CASE WHEN P.TIPO_PROC_NORM = 'ACEITE'                                     THEN P.DATA END) AS DT_ACEITE,
  MIN(CASE WHEN P.TIPO_PROC_NORM IN ('ESTOU NO SITE','ESTOU NA FALHA')          THEN P.DATA END) AS DT_SITE_OK,
  MIN(CASE WHEN P.TIPO_PROC_NORM = 'ESTOU NO SITE (FORA DE ALCANCE)'            THEN P.DATA END) AS DT_SITE_FORA,
  MIN(CASE WHEN P.TIPO_PROC_NORM = 'PRE-BAIXA'                                  THEN P.DATA END) AS DT_PREBAIXA,
  MAX(P.DATA) AS DT_ULTIMO_MOV
INTO #EVT_MIN
FROM #PROC_PERIODO P
GROUP BY P.NUM_OS, P.RE;

CREATE CLUSTERED INDEX CX_EVT_MIN ON #EVT_MIN (NUM_OS, RE);

-- GEO do primeiro ACEITE
DROP TABLE IF EXISTS #ACEITE_GEO;
SELECT
  A.NUM_OS,
  A.RE,
  P.GEO_PROC AS GEO_ACEITE
INTO #ACEITE_GEO
FROM #EVT_MIN A
JOIN #PROC_PERIODO P
  ON P.NUM_OS = A.NUM_OS
 AND P.RE = A.RE
 AND P.TIPO_PROC_NORM = 'ACEITE'
 AND P.DATA = A.DT_ACEITE;

CREATE CLUSTERED INDEX CX_ACEITE_GEO ON #ACEITE_GEO (NUM_OS, RE);

-- GEO do primeiro SITE válido
DROP TABLE IF EXISTS #SITE_OK_GEO;
SELECT
  S.NUM_OS,
  S.RE,
  P.GEO_PROC AS GEO_SITE_OK
INTO #SITE_OK_GEO
FROM #EVT_MIN S
JOIN #PROC_PERIODO P
  ON P.NUM_OS = S.NUM_OS
 AND P.RE = S.RE
 AND P.TIPO_PROC_NORM IN ('ESTOU NO SITE','ESTOU NA FALHA')
 AND P.DATA = S.DT_SITE_OK;

CREATE CLUSTERED INDEX CX_SITE_OK_GEO ON #SITE_OK_GEO (NUM_OS, RE);

-- Flag pausa
DROP TABLE IF EXISTS #PAUSA_FLAG;
SELECT
  P.NUM_OS,
  P.RE,
  1 AS FL_TEVE_PAUSA
INTO #PAUSA_FLAG
FROM #PROC_PERIODO P
WHERE P.TIPO_PROC_NORM LIKE 'PAUSA%'
GROUP BY P.NUM_OS, P.RE;

CREATE CLUSTERED INDEX CX_PAUSA_FLAG ON #PAUSA_FLAG (NUM_OS, RE);

/* ============================================================
   [V0.6.4] Montagem do #EVT final (Usando RE como chave)
   ============================================================ */
DROP TABLE IF EXISTS #EVT;
SELECT
  DU.NUM_OS,
  DU.RE,
  -- Recupera o Nome para exibição baseado no RE
  COALESCE(T_UNI.NOME_TECNICO, T_DUP.NOME_TECNICO, 'NOME NAO IDENTIFICADO') AS NOME_TECNICO,
  
  -- Enriquecimentos
  COALESCE(T_UNI.EMPRESA, #OP_ONE.EMPRESA, T_DUP.EMPRESA, 'EMPRESA NAO IDENTIFICADA') AS EMPRESA_OS,
  COALESCE(T_UNI.UF_TEC,  T_DUP.UF_TEC,  #OP_ONE.UF_EVENTO, 'UF NAO IDENTIFICADA')    AS UF_TEC,
  COALESCE(T_UNI.REGIONAL,#OP_ONE.REGIONAL_EVENTO, 'REGIONAL NAO IDENTIFICADA')       AS REGIONAL_OS,
  COALESCE(T_UNI.TIPO_TEC, T_DUP.TIPO_TEC, 'TIPO NAO IDENTIFICADO')                   AS TIPO_TEC,

  EM.DT_ATRIB,
  EM.DT_ACEITE,
  EM.DT_SITE_OK      AS DT_SITE_VALIDO,
  EM.DT_SITE_FORA    AS DT_SITE_FORA,
  EM.DT_PREBAIXA,
  EM.DT_ULTIMO_MOV   AS DT_ULTIMO_MOVIMENTO_OS,
  CASE WHEN PF.FL_TEVE_PAUSA = 1 THEN 1 ELSE 0 END AS FL_TEVE_PAUSA,

  TRY_CAST(AG.GEO_ACEITE.Lat     AS FLOAT) AS LAT_ACEITE,
  TRY_CAST(AG.GEO_ACEITE.Long    AS FLOAT) AS LONG_ACEITE,
  TRY_CAST(SG.GEO_SITE_OK.Lat    AS FLOAT) AS LAT_SITE,
  TRY_CAST(SG.GEO_SITE_OK.Long   AS FLOAT) AS LONG_SITE
INTO #EVT
FROM #DU DU
LEFT JOIN #OP_ONE            ON #OP_ONE.NUM_OS   = DU.NUM_OS
-- JOIN CRUCIAL: RE do PROC = RE_MATRICULA da DIMENSAO
LEFT JOIN #DIM_TECNICOS_FINAL T_UNI ON T_UNI.RE_MATRICULA = DU.RE AND T_UNI.FL_RE_UNICO = 1
LEFT JOIN #DIM_TECNICOS_FINAL T_DUP ON T_DUP.RE_MATRICULA = DU.RE AND T_DUP.FL_RE_UNICO = 0 AND T_DUP.EMPRESA = #OP_ONE.EMPRESA
LEFT JOIN #EVT_MIN EM        ON EM.NUM_OS        = DU.NUM_OS AND EM.RE    = DU.RE
LEFT JOIN #ACEITE_GEO AG     ON AG.NUM_OS        = DU.NUM_OS AND AG.RE    = DU.RE
LEFT JOIN #SITE_OK_GEO SG    ON SG.NUM_OS        = DU.NUM_OS AND SG.RE    = DU.RE
LEFT JOIN #PAUSA_FLAG PF     ON PF.NUM_OS        = DU.NUM_OS AND PF.RE    = DU.RE;


/* =========================
   STEP 2 — FLAGS & AJUSTES
   ========================= */
DROP TABLE IF EXISTS #FLAGS;
SELECT
  NUM_OS, RE, NOME_TECNICO, EMPRESA_OS, REGIONAL_OS, UF_TEC, TIPO_TEC,
  CASE WHEN DT_ATRIB         IS NOT NULL THEN 1 ELSE 0 END AS FL_ATRIB,
  CASE WHEN DT_ACEITE        IS NOT NULL THEN 1 ELSE 0 END AS FL_ACEITE,
  CASE WHEN DT_SITE_VALIDO IS NOT NULL THEN 1 ELSE 0 END AS FL_SITE_VALIDO,
  CASE WHEN DT_SITE_FORA     IS NOT NULL THEN 1 ELSE 0 END AS FL_SITE_FORA,
  CASE WHEN (DT_SITE_VALIDO IS NOT NULL OR DT_SITE_FORA IS NOT NULL) THEN 1 ELSE 0 END AS FL_SITE_TOTAL,
  CASE WHEN DT_PREBAIXA      IS NOT NULL THEN 1 ELSE 0 END AS FL_PREBAIXA,
  DT_ACEITE, DT_SITE_VALIDO, DT_PREBAIXA, LAT_ACEITE, LONG_ACEITE, LAT_SITE, LONG_SITE, DT_ATRIB
INTO #FLAGS
FROM #EVT;

DROP TABLE IF EXISTS #SEM_ATUACAO;
SELECT
  E.NUM_OS, E.RE,
  CASE WHEN E.FL_ATRIB = 1 AND E.FL_ACEITE = 0
        AND NOT EXISTS (
          SELECT 1
          FROM #PROC_PERIODO P
          WHERE P.NUM_OS = E.NUM_OS
            AND P.TIPO_PROC_NORM IN ('ACEITE','ESTOU NO SITE','ESTOU NA FALHA','PRE-BAIXA')
        )
       THEN 1 ELSE 0 END AS FL_SEM_ATUACAO
INTO #SEM_ATUACAO
FROM #FLAGS E;

DROP TABLE IF EXISTS #ESTEIRA_AJUST;
SELECT
  EO.NUM_OS, EO.RE,
  CASE WHEN SA.FL_SEM_ATUACAO = 1 THEN 0 ELSE EO.FL_ATRIB END         AS ATRIB_AJUST,
  CASE WHEN SA.FL_SEM_ATUACAO = 1 THEN 0 ELSE EO.FL_ACEITE END        AS ACEITE_AJUST,
  CASE WHEN SA.FL_SEM_ATUACAO = 1 THEN 0 ELSE EO.FL_SITE_VALIDO END  AS SITE_VALIDO_AJUST,
  CASE WHEN SA.FL_SEM_ATUACAO = 1 THEN 0 ELSE EO.FL_SITE_FORA END     AS SITE_FORA_AJUST,
  CASE WHEN SA.FL_SEM_ATUACAO = 1 THEN 0 ELSE EO.FL_SITE_TOTAL END    AS SITE_TOTAL_AJUST,
  CASE WHEN SA.FL_SEM_ATUACAO = 1 THEN 0 ELSE EO.FL_PREBAIXA END      AS PREBAIXA_AJUST
INTO #ESTEIRA_AJUST
FROM #FLAGS EO
LEFT JOIN #SEM_ATUACAO SA
  ON SA.NUM_OS = EO.NUM_OS AND SA.RE = EO.RE;

/* =========================
   STEP 3 — DEFLATORES
   ========================= */
DROP TABLE IF EXISTS #DEF_FORA_SITE;
SELECT A.NUM_OS, A.RE,
  CASE WHEN A.FL_SITE_FORA = 1
        AND NOT EXISTS (
          SELECT 1 FROM #EVT B
          WHERE B.NUM_OS = A.NUM_OS AND B.RE = A.RE AND B.DT_SITE_VALIDO IS NOT NULL
        )
       THEN 1 ELSE 0 END AS FL_FORA_SITE_SEM_CORR
INTO #DEF_FORA_SITE
FROM #FLAGS A;

DROP TABLE IF EXISTS #DEF_REATRIB;
SELECT DISTINCT A.NUM_OS, A.RE AS TEC_ORIGINAL,
  CASE WHEN A.DT_ACEITE IS NOT NULL
        AND EXISTS (SELECT 1 FROM #EVT B WHERE B.NUM_OS = A.NUM_OS AND B.RE <> A.RE AND B.DT_ACEITE > A.DT_ACEITE)
        AND (A.DT_PREBAIXA IS NULL OR A.DT_PREBAIXA < (SELECT MAX(DT_PREBAIXA) FROM #EVT C WHERE C.NUM_OS = A.NUM_OS))
       THEN 1 ELSE 0 END AS FL_REATRIB
INTO #DEF_REATRIB
FROM #EVT A;

DROP TABLE IF EXISTS #DEF_PERDA;
SELECT A.NUM_OS, A.RE,
  CASE WHEN A.FL_ATRIB = 1 AND A.FL_ACEITE = 0
        AND NOT EXISTS (
          SELECT 1 FROM #PROC_PERIODO P
          WHERE P.NUM_OS = A.NUM_OS
            AND P.TIPO_PROC_NORM IN ('ACEITE','ESTOU NO SITE','ESTOU NA FALHA','PRE-BAIXA')
        )
       THEN 1 ELSE 0 END AS FL_PERDA_ATRIB
INTO #DEF_PERDA
FROM #FLAGS A;

DROP TABLE IF EXISTS #DEF_ABANDONO;
SELECT A.NUM_OS, A.RE,
  CASE WHEN A.DT_ACEITE IS NOT NULL AND A.DT_PREBAIXA IS NULL
        AND EXISTS (
            SELECT 1 FROM #EVT B
            WHERE B.NUM_OS = A.NUM_OS AND B.RE <> A.RE
              AND COALESCE(B.DT_ACEITE, B.DT_SITE_VALIDO, B.DT_PREBAIXA) > A.DT_ACEITE
        )
       THEN 1 ELSE 0 END AS FL_ABANDONO
INTO #DEF_ABANDONO
FROM #EVT A;

DROP TABLE IF EXISTS #DEF_ONERADA;
SELECT A.NUM_OS, A.RE,
  CASE WHEN A.DT_ATRIB IS NOT NULL AND A.DT_ACEITE IS NULL
        AND EXISTS (
          SELECT 1 FROM #EVT B
          WHERE B.NUM_OS = A.NUM_OS AND B.RE <> A.RE AND B.DT_ACEITE > A.DT_ATRIB
        )
       THEN 1 ELSE 0 END AS FL_ATRIB_ONERADA
INTO #DEF_ONERADA
FROM #EVT A;

DROP TABLE IF EXISTS #DEF_TELEPORT;
SELECT A.NUM_OS, A.RE,
  CASE WHEN A.LAT_ACEITE IS NOT NULL AND A.LAT_SITE IS NOT NULL
            AND DATEDIFF(MINUTE, A.DT_ACEITE, A.DT_SITE_VALIDO) >= 0
       THEN CASE WHEN (geography::Point(A.LAT_ACEITE, A.LONG_ACEITE, 4326)
                      .STDistance(geography::Point(A.LAT_SITE, A.LONG_SITE, 4326)) / 1000.0)
                    / NULLIF((DATEDIFF(MINUTE, A.DT_ACEITE, A.DT_SITE_VALIDO) / 60.0), 0) > 150
            THEN 1 ELSE 0 END
       ELSE 0 END AS FL_TELEPORT,
  CASE WHEN A.LAT_ACEITE IS NOT NULL AND A.LAT_SITE IS NOT NULL
       THEN geography::Point(A.LAT_ACEITE, A.LONG_ACEITE, 4326)
            .STDistance(geography::Point(A.LAT_SITE, A.LONG_SITE, 4326))
       ELSE 0 END AS DIST_METROS
INTO #DEF_TELEPORT
FROM #FLAGS A;

/* =========================
   STEP 4 — CICLOS
   ========================= */
DROP TABLE IF EXISTS #CICLOS_RAW;
SELECT
  E.NUM_OS, E.RE, E.DT_PREBAIXA,
  CASE WHEN E.DT_ATRIB IS NOT NULL AND E.DT_ACEITE IS NOT NULL AND E.DT_SITE_VALIDO IS NOT NULL AND E.DT_PREBAIXA IS NOT NULL
       THEN 1 ELSE 0 END AS IS_TECNICAMENTE_COMPLETO
INTO #CICLOS_RAW
FROM #EVT E;

DROP TABLE IF EXISTS #CICLO_FINAL_OS;
SELECT NUM_OS, MAX(DT_PREBAIXA) AS DT_PREBAIXA_FINAL
INTO #CICLO_FINAL_OS
FROM #EVT
WHERE DT_PREBAIXA IS NOT NULL
GROUP BY NUM_OS;

DROP TABLE IF EXISTS #CICLOS_MARCADOS;
SELECT
  C.NUM_OS, C.RE,
  CASE WHEN C.DT_PREBAIXA IS NOT NULL AND C.DT_PREBAIXA = F.DT_PREBAIXA_FINAL THEN 1 ELSE 0 END AS FL_CICLO_FINAL,
  CASE WHEN C.IS_TECNICAMENTE_COMPLETO = 1 AND (C.DT_PREBAIXA IS NULL OR C.DT_PREBAIXA <> F.DT_PREBAIXA_FINAL) THEN 1 ELSE 0 END AS FL_CICLO_COMPLETO
INTO #CICLOS_MARCADOS
FROM #CICLOS_RAW C
LEFT JOIN #CICLO_FINAL_OS F ON F.NUM_OS = C.NUM_OS;

/* =========================
   STEP 5 — TEMPOS
   ========================= */
DROP TABLE IF EXISTS #TEMPOS;
SELECT
  E.NUM_OS, E.RE,
  DATEDIFF(MINUTE, E.DT_ATRIB,  E.DT_ACEITE)   AS TMP_ATRIB_ACEITE,
  DATEDIFF(MINUTE, E.DT_ACEITE, E.DT_PREBAIXA) AS TMP_ACEITE_PRE,
  CASE
    WHEN E.DT_ACEITE IS NULL OR E.DT_PREBAIXA IS NULL OR (DATEDIFF(MINUTE, E.DT_ACEITE, E.DT_PREBAIXA)) < @Treshold_Min THEN 0.00
    WHEN DATEDIFF(MINUTE, E.DT_ACEITE, E.DT_PREBAIXA) <= @Tier1_Min THEN @Pt_Tier1
    WHEN DATEDIFF(MINUTE, E.DT_ACEITE, E.DT_PREBAIXA) <= @Tier2_Min THEN @Pt_Tier2
    WHEN DATEDIFF(MINUTE, E.DT_ACEITE, E.DT_PREBAIXA) <= @Tier3_Min THEN @Pt_Tier3
    WHEN DATEDIFF(MINUTE, E.DT_ACEITE, E.DT_PREBAIXA) <= @Tier4_Min THEN @Pt_Tier4
    ELSE @Pt_Tier5
  END AS PONTOS_TEMPO_GERADOS_OS,
  CASE WHEN E.DT_ACEITE IS NOT NULL
            AND (E.DT_PREBAIXA IS NULL OR DATEDIFF(MINUTE, E.DT_ACEITE, E.DT_PREBAIXA) < @Treshold_Min)
       THEN 1 ELSE 0 END AS concluidos_tempo_pendente,
  CASE WHEN E.DT_ACEITE IS NOT NULL AND E.DT_PREBAIXA IS NOT NULL AND DATEDIFF(MINUTE, E.DT_ACEITE, E.DT_PREBAIXA) > @Treshold_Min AND DATEDIFF(MINUTE, E.DT_ACEITE, E.DT_PREBAIXA) <= @Tier1_Min THEN 1 ELSE 0 END AS concluidos_tempo_1,
  CASE WHEN E.DT_ACEITE IS NOT NULL AND E.DT_PREBAIXA IS NOT NULL AND DATEDIFF(MINUTE, E.DT_ACEITE, E.DT_PREBAIXA) > @Tier1_Min AND DATEDIFF(MINUTE, E.DT_ACEITE, E.DT_PREBAIXA) <= @Tier2_Min THEN 1 ELSE 0 END AS concluidos_tempo_2,
  CASE WHEN E.DT_ACEITE IS NOT NULL AND E.DT_PREBAIXA IS NOT NULL AND DATEDIFF(MINUTE, E.DT_ACEITE, E.DT_PREBAIXA) > @Tier2_Min AND DATEDIFF(MINUTE, E.DT_ACEITE, E.DT_PREBAIXA) <= @Tier3_Min THEN 1 ELSE 0 END AS concluidos_tempo_3,
  CASE WHEN E.DT_ACEITE IS NOT NULL AND E.DT_PREBAIXA IS NOT NULL AND DATEDIFF(MINUTE, E.DT_ACEITE, E.DT_PREBAIXA) > @Tier3_Min AND DATEDIFF(MINUTE, E.DT_ACEITE, E.DT_PREBAIXA) <= @Tier4_Min THEN 1 ELSE 0 END AS concluidos_tempo_4,
  CASE WHEN E.DT_ACEITE IS NOT NULL AND E.DT_PREBAIXA IS NOT NULL AND DATEDIFF(MINUTE, E.DT_ACEITE, E.DT_PREBAIXA) > @Tier4_Min THEN 1 ELSE 0 END AS concluidos_tempo_5
INTO #TEMPOS
FROM #EVT E;

DROP TABLE IF EXISTS #TEMPOS_TEC;
SELECT
  T.RE,
  AVG(T.TMP_ATRIB_ACEITE) AS TMP_MED_ATRIB_ACEITE,
  AVG(T.TMP_ACEITE_PRE)   AS TMP_MED_ACEITE_PRE,
  SUM(T.PONTOS_TEMPO_GERADOS_OS) AS TOTAL_PONTOS_TEMPO,
  SUM(T.concluidos_tempo_1) AS concluidos_tempo_1,
  SUM(T.concluidos_tempo_2) AS concluidos_tempo_2,
  SUM(T.concluidos_tempo_3) AS concluidos_tempo_3,
  SUM(T.concluidos_tempo_4) AS concluidos_tempo_4,
  SUM(T.concluidos_tempo_5) AS concluidos_tempo_5,
  SUM(T.concluidos_tempo_pendente) AS concluidos_tempo_pendente
INTO #TEMPOS_TEC
FROM #TEMPOS T
WHERE NOT EXISTS (
  SELECT 1 FROM #SEM_ATUACAO SA
  WHERE SA.NUM_OS = T.NUM_OS AND SA.RE = T.RE AND SA.FL_SEM_ATUACAO = 1
)
GROUP BY T.RE;

/* =========================
   STEP 6 — AGREGAÇÕES
   ========================= */
DROP TABLE IF EXISTS #ESTEIRA_TEC_AGG;
SELECT
  T.RE,
  MAX(T.NOME_TECNICO)  AS NOME_TECNICO, -- Carrega o nome para o final
  MAX(T.EMPRESA_OS)    AS EMPRESA_PRINCIPAL,
  MAX(T.REGIONAL_OS)   AS REGIONAL_PRINCIPAL,
  MAX(T.DT_PREBAIXA)   AS DT_ULTIMA_OS_CONCLUIDA,
  SUM(O.FL_ATRIB)      AS ATRIB_BRUTO,
  SUM(O.FL_ACEITE)     AS ACEITE_BRUTO,
  SUM(O.FL_SITE_TOTAL) AS SITE_TOTAL_BRUTO,
  SUM(O.FL_SITE_VALIDO)AS SITE_VALIDO_BRUTO,
  SUM(O.FL_SITE_FORA)  AS SITE_FORA_BRUTO,
  SUM(O.FL_PREBAIXA)   AS PREBAIXA_BRUTO,
  SUM(A.ATRIB_AJUST)      AS ATRIB_AJUST,
  SUM(A.ACEITE_AJUST)     AS ACEITE_AJUST,
  SUM(A.SITE_TOTAL_AJUST) AS SITE_TOTAL_AJUST,
  SUM(A.SITE_VALIDO_AJUST)AS SITE_VALIDO_AJUST,
  SUM(A.SITE_FORA_AJUST)  AS SITE_FORA_AJUST,
  SUM(A.PREBAIXA_AJUST)   AS PREBAIXA_AJUST
INTO #ESTEIRA_TEC_AGG
FROM (SELECT DISTINCT RE, NUM_OS, EMPRESA_OS, REGIONAL_OS, DT_PREBAIXA, NOME_TECNICO FROM #FLAGS) T
LEFT JOIN #FLAGS O         ON O.NUM_OS = T.NUM_OS AND O.RE = T.RE
LEFT JOIN #ESTEIRA_AJUST A ON A.NUM_OS = T.NUM_OS AND A.RE = T.RE
GROUP BY T.RE;

DROP TABLE IF EXISTS #CICLOS_TEC_AGG;
SELECT
  C.RE,
  SUM(C.FL_CICLO_COMPLETO) AS QTD_CICLOS_COMPLETOS_BR,
  SUM(C.FL_CICLO_FINAL)    AS QTD_CICLOS_FINAIS_BR,
  SUM(CASE WHEN SA.FL_SEM_ATUACAO = 1 THEN 0 ELSE C.FL_CICLO_COMPLETO END) AS QTD_CICLOS_COMPLETOS_AJ,
  SUM(CASE WHEN SA.FL_SEM_ATUACAO = 1 THEN 0 ELSE C.FL_CICLO_FINAL    END) AS QTD_CICLOS_FINAIS_AJ
INTO #CICLOS_TEC_AGG
FROM #CICLOS_MARCADOS C
LEFT JOIN #SEM_ATUACAO SA ON SA.NUM_OS = C.NUM_OS AND SA.RE = C.RE
GROUP BY C.RE;

DROP TABLE IF EXISTS #DEF_TEC_AGG;
SELECT
  U.RE,
  SUM(ISNULL(F.FL_FORA_SITE_SEM_CORR,0)) AS QTD_FORA_SITE_SEM_CORR,
  SUM(ISNULL(R.FL_REATRIB,0))            AS QTD_REATRIB,
  SUM(ISNULL(P.FL_PERDA_ATRIB,0))        AS QTD_PERDA_ATRIB,
  SUM(ISNULL(B.FL_ABANDONO,0))           AS QTD_ABANDONOS,
  SUM(ISNULL(O.FL_ATRIB_ONERADA,0))      AS QTD_ATRIB_ONERADAS,
  SUM(ISNULL(TP.FL_TELEPORT,0))          AS QTD_TELEPORT,
  AVG(ISNULL(TP.DIST_METROS,0))          AS DISTANCIA_MEDIA_METROS
INTO #DEF_TEC_AGG
FROM (SELECT DISTINCT RE, NUM_OS FROM #FLAGS) U
LEFT JOIN #DEF_FORA_SITE F ON F.NUM_OS = U.NUM_OS AND F.RE = U.RE
LEFT JOIN #DEF_REATRIB R    ON R.NUM_OS = U.NUM_OS AND R.TEC_ORIGINAL = U.RE
LEFT JOIN #DEF_PERDA P      ON P.NUM_OS = U.NUM_OS AND P.RE = U.RE
LEFT JOIN #DEF_ABANDONO B   ON B.NUM_OS = U.NUM_OS AND B.RE = U.RE
LEFT JOIN #DEF_ONERADA O    ON O.NUM_OS = U.NUM_OS AND O.RE = U.RE
LEFT JOIN #DEF_TELEPORT TP  ON TP.NUM_OS = U.NUM_OS AND TP.RE = U.RE
GROUP BY U.RE;

DROP TABLE IF EXISTS #BASE_TEC_RAW;
SELECT
  U.RE,
  U.NOME_TECNICO, -- Nome preservado
  U.UF, U.TIPO_TEC,
  E.EMPRESA_PRINCIPAL, E.REGIONAL_PRINCIPAL, E.DT_ULTIMA_OS_CONCLUIDA,
  E.ATRIB_BRUTO, E.ATRIB_AJUST,
  E.ACEITE_BRUTO, E.ACEITE_AJUST,
  E.SITE_TOTAL_BRUTO, E.SITE_TOTAL_AJUST,
  E.SITE_VALIDO_BRUTO, E.SITE_VALIDO_AJUST,
  E.SITE_FORA_BRUTO, E.SITE_FORA_AJUST,
  E.PREBAIXA_BRUTO, E.PREBAIXA_AJUST,
  ISNULL(C.QTD_CICLOS_COMPLETOS_BR,0) AS CICLOS_COMPLETOS_BR,
  ISNULL(C.QTD_CICLOS_FINAIS_BR,0)    AS CICLOS_FINAIS_BR,
  ISNULL(C.QTD_CICLOS_COMPLETOS_AJ,0) AS CICLOS_COMPLETOS_AJ,
  ISNULL(C.QTD_CICLOS_FINAIS_AJ,0)    AS CICLOS_FINAIS_AJ,
  ISNULL(D.QTD_FORA_SITE_SEM_CORR,0)  AS QTD_FORA_SITE_SEM_CORR,
  ISNULL(D.QTD_REATRIB,0)             AS QTD_REATRIB,
  ISNULL(D.QTD_PERDA_ATRIB,0)         AS QTD_PERDA_ATRIB,
  ISNULL(D.QTD_ABANDONOS,0)           AS QTD_ABANDONOS,
  ISNULL(D.QTD_ATRIB_ONERADAS,0)      AS QTD_ATRIB_ONERADAS,
  ISNULL(D.QTD_TELEPORT,0)            AS QTD_TELEPORT,
  ISNULL(D.DISTANCIA_MEDIA_METROS,0)  AS DISTANCIA_MEDIA_METROS,
  ISNULL(T.TOTAL_PONTOS_TEMPO, 0)     AS TOTAL_PONTOS_TEMPO,
  T.TMP_MED_ATRIB_ACEITE, T.TMP_MED_ACEITE_PRE
INTO #BASE_TEC_RAW
FROM (SELECT DISTINCT RE, NOME_TECNICO, UF_TEC AS UF, TIPO_TEC FROM #FLAGS) U
LEFT JOIN #ESTEIRA_TEC_AGG E ON E.RE = U.RE
LEFT JOIN #CICLOS_TEC_AGG C  ON C.RE = U.RE
LEFT JOIN #DEF_TEC_AGG D     ON D.RE = U.RE
LEFT JOIN #TEMPOS_TEC T      ON T.RE = U.RE;

DROP TABLE IF EXISTS #BASE_DEDUP;
SELECT DISTINCT * INTO #BASE_DEDUP FROM #BASE_TEC_RAW;

DROP TABLE IF EXISTS #SCORE_SEGREGADO;
SELECT
  W.RE,
  (@wEtapa_Atrib  * ISNULL(W.ATRIB_AJUST,0)
 + @wEtapa_Aceite * ISNULL(W.ACEITE_AJUST,0)
 + @wEtapa_Site   * ISNULL(W.SITE_VALIDO_AJUST,0)
 + @wEtapa_Baixa  * ISNULL(W.PREBAIXA_AJUST,0)
 + @wBonus_Completo * ISNULL(W.CICLOS_COMPLETOS_AJ,0)
 + @wBonus_Final    * ISNULL(W.CICLOS_FINAIS_AJ,0)) AS PTS_PRODUTIVIDADE,
  ISNULL(W.TOTAL_PONTOS_TEMPO, 0) AS PTS_TEMPO,
  (@pen_Reatrib * ISNULL(W.QTD_REATRIB,0)
 + @pen_Perda   * ISNULL(W.QTD_PERDA_ATRIB,0)
 + @pen_Aband   * ISNULL(W.QTD_ABANDONOS,0)
 + @pen_Fora    * ISNULL(W.QTD_FORA_SITE_SEM_CORR,0)
 + @pen_Onera   * ISNULL(W.QTD_ATRIB_ONERADAS,0)
 + @pen_Teleport* ISNULL(W.QTD_TELEPORT,0)) AS PTS_DEFLACAO
INTO #SCORE_SEGREGADO
FROM #BASE_DEDUP W;

/* =========================
   STEP 7 — LOGIN & SILVER FINAL (Layout Rigoroso)
   ========================= */
DROP TABLE IF EXISTS #LOGIN_CHECK;
WITH ULTIMO_LOGIN AS (
  SELECT RE, MAX(DATA) AS DT_ULTIMO_LOGIN_PERIODO
  FROM #PROC_PERIODO
  GROUP BY RE
),
LOGIN_FLAG AS (
  SELECT P.RE, 1 AS FL_LOGIN_RECENTE
  FROM #PROC_LOGIN_WINDOW P
  GROUP BY P.RE
)
SELECT
  COALESCE(U.RE, F.RE) AS RE,
  U.DT_ULTIMO_LOGIN_PERIODO       AS DT_ULTIMO_LOGIN_GERAL,
  ISNULL(F.FL_LOGIN_RECENTE, 0)   AS FL_LOGIN_RECENTE
INTO #LOGIN_CHECK
FROM ULTIMO_LOGIN U
FULL OUTER JOIN LOGIN_FLAG F ON F.RE = U.RE;

DROP TABLE IF EXISTS #SILVER_FINAL;
SELECT
  '1. GOLD FINAL' AS RELATORIO,
  CAST(W.RE AS VARCHAR(20)) AS RE, -- [Layout Fix] RE como VARCHAR(20)
  W.NOME_TECNICO AS USUARIO,
  W.EMPRESA_PRINCIPAL AS EMPRESA,
  W.REGIONAL_PRINCIPAL AS REGIONAL,
  W.UF,
  W.TIPO_TEC,
  ISNULL(LC.FL_LOGIN_RECENTE, 0) AS LOGIN_7D,
  LC.DT_ULTIMO_LOGIN_GERAL       AS DT_ULTIMO_LOGIN,
  W.DT_ULTIMA_OS_CONCLUIDA,
  (SELECT MAX(v) FROM (VALUES (W.ATRIB_BRUTO),(W.ACEITE_BRUTO),(W.SITE_TOTAL_BRUTO)) AS t(v)) AS TOTAL_OPORTUNIDADES_BRUTO,
  (SELECT MAX(v) FROM (VALUES (W.ATRIB_AJUST),(W.ACEITE_AJUST),(W.SITE_TOTAL_AJUST)) AS t(v)) AS TOTAL_OPORTUNIDADES_AJUSTADO,
  W.ATRIB_BRUTO,
  W.ATRIB_AJUST,
  W.ACEITE_BRUTO,
  W.ACEITE_AJUST,
  W.SITE_TOTAL_BRUTO AS NO_SITE_TOTAL_BRUTO,
  W.SITE_TOTAL_AJUST AS NO_SITE_TOTAL_AJUST,
  W.SITE_VALIDO_BRUTO AS NO_SITE_CORRETO_BRUTO,
  W.SITE_VALIDO_AJUST AS NO_SITE_CORRETO_AJUST,
  W.SITE_FORA_BRUTO   AS NO_SITE_ERRADO_BRUTO,
  W.SITE_FORA_AJUST   AS NO_SITE_ERRADO_AJUST,
  W.PREBAIXA_BRUTO,
  W.PREBAIXA_AJUST,
  (W.CICLOS_COMPLETOS_BR + W.CICLOS_FINAIS_BR) AS CICLOS_TOTAIS_BRUTO,
  (W.CICLOS_COMPLETOS_AJ + W.CICLOS_FINAIS_AJ) AS CICLOS_TOTAIS_AJUSTADO,
  W.CICLOS_COMPLETOS_BR,
  W.CICLOS_COMPLETOS_AJ,
  W.CICLOS_FINAIS_BR,
  W.CICLOS_FINAIS_AJ,
  CAST(FLOOR(W.TMP_MED_ATRIB_ACEITE * 100) / 100.0 AS DECIMAL(10,2)) AS MEDIA_TEMPO_ATRIB_ACEITE,
  CAST(FLOOR(W.TMP_MED_ACEITE_PRE  * 100) / 100.0 AS DECIMAL(10,2)) AS MEDIA_TEMPO_ACEITE_PREBAIXA,
  ISNULL(T.concluidos_tempo_1, 0) AS concluidos_tempo_1,
  ISNULL(T.concluidos_tempo_2, 0) AS concluidos_tempo_2,
  ISNULL(T.concluidos_tempo_3, 0) AS concluidos_tempo_3,
  ISNULL(T.concluidos_tempo_4, 0) AS concluidos_tempo_4,
  ISNULL(T.concluidos_tempo_5, 0) AS concluidos_tempo_5,
  ISNULL(T.concluidos_tempo_pendente, 0) AS concluidos_tempo_sem_baixa,
  CAST(FLOOR((W.DISTANCIA_MEDIA_METROS / 1000.0) * 100) / 100.0 AS DECIMAL(10,2)) AS DISTANCIA_MEDIA_OS_KM,
  
  -- Colunas extras do layout original
  CAST(S.PTS_PRODUTIVIDADE AS DECIMAL(10,2)) AS NOTA_PRODUTIVIDADE,
  CAST(S.PTS_TEMPO AS DECIMAL(10,2))         AS NOTA_TEMPO,
  CAST(S.PTS_DEFLACAO AS DECIMAL(10,2))      AS NOTA_DEFLATOR,
  
  -- Coluna anomes
  CONVERT(VARCHAR(6), @Carga_Ref_Data, 112) AS anomes,
  CONCAT(CONVERT(char(6), @Carga_Ref_Data, 112),
         RIGHT('00' + CAST(DATEPART(ISO_WEEK, @Carga_Ref_Data) AS varchar(2)), 2)) AS anomessemana,
  CAST(@Carga_Ref_Data AS DATETIME) AS max_data_anomes,

  CAST(
    ( FLOOR(
        (CASE WHEN (SELECT MAX(v) FROM (VALUES (W.ATRIB_AJUST),(W.ACEITE_AJUST),(W.SITE_TOTAL_AJUST)) AS t(v)) > 0
              THEN (S.PTS_PRODUTIVIDADE / (SELECT MAX(v) FROM (VALUES (W.ATRIB_AJUST),(W.ACEITE_AJUST),(W.SITE_TOTAL_AJUST)) AS t(v))) * 100.0
              ELSE 0 END) * @Peso_Dimensao_Prod
        + (CASE WHEN W.ACEITE_AJUST > 0
                THEN (S.PTS_TEMPO / NULLIF(W.ACEITE_AJUST * 1.0, 0)) * 100.0
                ELSE 0 END) * @Peso_Dimensao_Tempo
      )
      + S.PTS_DEFLACAO * 100
    ) / 100.0
    AS DECIMAL(10,2)
  ) AS NOTA_FINAL,

  CAST(FLOOR(S.PTS_PRODUTIVIDADE * 100) / 100.0 AS DECIMAL(10,2)) AS KEY_SCORE_PROD,
  CAST(FLOOR(S.PTS_TEMPO         * 100) / 100.0 AS DECIMAL(10,2)) AS KEY_SCORE_TIME,
  CAST(FLOOR((S.PTS_PRODUTIVIDADE + S.PTS_TEMPO + S.PTS_DEFLACAO) * 100) / 100.0 AS DECIMAL(10,2)) AS KEY_SCORE,

  @VersaoRegra AS VERSAO,
  @DataExecucao AS PROCESSADO_EM
INTO #SILVER_FINAL
FROM #BASE_DEDUP W
JOIN #SCORE_SEGREGADO S ON S.RE = W.RE
LEFT JOIN #LOGIN_CHECK LC ON LC.RE = W.RE
LEFT JOIN #TEMPOS_TEC T   ON T.RE = W.RE
ORDER BY NOTA_FINAL DESC;

/* =========================
   STEP 8 — PERSISTÊNCIA GOLD
   ========================= */
-- [V0.6.4] Fix Schema Drift + Garantia de Ordem
IF OBJECT_ID('GENESIS.PROD.TBL_RANK_TEC', 'U') IS NOT NULL
BEGIN
    -- Verifica se a coluna RE existe na tabela destino E se o tipo é compatível (se necessário)
    -- Para segurança total, renomeamos se a coluna RE não existir.
    IF COL_LENGTH('GENESIS.PROD.TBL_RANK_TEC', 'RE') IS NULL
    BEGIN
        DECLARE @BkpName NVARCHAR(128) = 'TBL_RANK_TEC_BKP_' + CONVERT(VARCHAR, GETDATE(), 112) + '_' + REPLACE(CONVERT(VARCHAR, GETDATE(), 108), ':', '');
        EXEC sp_rename 'GENESIS.PROD.TBL_RANK_TEC', @BkpName;
        PRINT 'ALERT: Tabela GENESIS.PROD.TBL_RANK_TEC renomeada para ' + @BkpName + ' para aplicar novo schema (Coluna RE).';
    END
END

IF OBJECT_ID('GENESIS.PROD.TBL_RANK_TEC', 'U') IS NULL
BEGIN
  SELECT * INTO GENESIS.PROD.TBL_RANK_TEC FROM #SILVER_FINAL;
  CREATE CLUSTERED INDEX CX_RANK_TEC ON GENESIS.PROD.TBL_RANK_TEC (RE, anomessemana);
END
ELSE
BEGIN
  INSERT INTO GENESIS.PROD.TBL_RANK_TEC
  SELECT * FROM #SILVER_FINAL;

  ;WITH d AS (
    SELECT RE, anomessemana, PROCESSADO_EM,
      ROW_NUMBER() OVER (
        PARTITION BY RE, anomessemana
        ORDER BY PROCESSADO_EM DESC, max_data_anomes DESC, VERSAO DESC, RE ASC
      ) AS rn
    FROM GENESIS.PROD.TBL_RANK_TEC
  )
  DELETE FROM d WHERE rn > 1;
END;

SELECT 'SUCESSO' AS STATUS, anomessemana, COUNT(*) AS TOTAL_LINHAS FROM GENESIS.PROD.TBL_RANK_TEC group by anomessemana;
